name: ci
on:
  push:
    branches-ignore: [main, dev]
jobs:
  ci:
    uses: x-farmer/.github/.github/workflows/node-app.yml@main
    with:
      run-lint: false
      test-cmd: "echo no-test"
      build-cmd: "echo no-build"
